Subphylum	Order	Family	Genus	Species	Wolbachia	Citation	Location	WolSpecies	LifeHistory	%infected	No.antsSampled
Insecta	Hymenoptera	Formicidae	Acromyrmex	rugosus	+	FROST & al. (2010)	?	?	?	0.90	43
Insecta	Hymenoptera	Formicidae	Acromyrmex	subterraneus subterraneus	+	FROST & al. (2010)	Brazil	?	Leaf cutting agriculture/polyandry	1	43
Insecta	Hymenoptera	Formicidae	Apterostigma	collare	–	FROST & al. (2010)	Panama	?	Fungus argiculture	0	37
Insecta	Hymenoptera	Formicidae	Apterostigma	dentigerum	+	FROST & al. (2010)	Panama	?	Fungus argiculture	1	32
Insecta	Hymenoptera	Formicidae	Cyphomyrmex	costatus	–	FROST & al. (2010)	Panama	?	Lower agriculture	0	32
Insecta	Hymenoptera	Formicidae	Cyphomyrmex	longiscapus	–	FROST & al. (2010)	Panama	?	Lower agriculture	0	18
Insecta	Hymenoptera	Formicidae	Cyphomyrmex	rimosus	–	FROST & al. (2010)	Panama	?	Lower agriculture	0	8
Insecta	Hymenoptera	Formicidae	Mycoceparus	smithii	–	FROST & al. (2010)	Panama	?	Lower agriculture	0	119
Insecta	Hymenoptera	Formicidae	Myrmicocrypta	ednaella	–	FROST & al. (2010)	Panama	?	Lower agriculture	0	16
Insecta	Hymenoptera	Formicidae	Sericomyrmex	cf.	amabilis	+	FROST & al. (2010)	Panama	?	Higher agriculture	1	21
Insecta	Hymenoptera	Formicidae	Sericomyrmex	amabilis	+	FROST & al. (2010)	Panama	?	Higher agriculture	0.07	92
Insecta	Hymenoptera	Formicidae	Trachymyrmex	cornetzi	–	FROST & al. (2010)	Panama	?	Higher agriculture	0	17
Insecta	Hymenoptera	Formicidae	Trachymyrmex	"Howard" (sp.	10)	+	FROST & al. (2010)	Panama	?	Higher agriculture	1	21
Insecta	Hymenoptera	Formicidae	Trachymyrmex	sp.	–	FROST & al. (2010)	Panama	?	Higher agriculture	0	14
Insecta	Hymenoptera	Formicidae	Trachymyrmex	cf.	zeteki	–	FROST & al. (2010)	Panama	?	Higher agriculture	0	94
Insecta	Hymenoptera	Formicidae	Camponotus	sp.	–	KITTAYAPONG & al. (2003)	Thailand	?	?	0	5
Insecta	Hymenoptera	Formicidae	Diacamma	sp.	–	KITTAYAPONG & al. (2003)	Thailand	?	?	0	3
Insecta	Hymenoptera	Formicidae	Oecophylla	smaragdina	–	KITTAYAPONG & al. (2003)	Thailand	?	?	0	4
Insecta	Hymenoptera	Formicidae	Polyrachis	sp. 1	–	KITTAYAPONG & al. (2003)	Thailand	?	?	0	1
Insecta	Hymenoptera	Formicidae	Polyrachis	sp. 2	+	KITTAYAPONG & al. (2003)	Thailand	?	?	1	1
Insecta	Hymenoptera	Formicidae	Polyrachis	sp. 3	–	KITTAYAPONG & al. (2003)	Thailand	?	?	0	1
Insecta	Hymenoptera	Formicidae	Polyrachis	sp. 4	–	KITTAYAPONG & al. (2003)	Thailand	?	?	0	3
Insecta	Hymenoptera	Formicidae	Solenopsis	sp.	+	KITTAYAPONG & al. (2003)	Thailand	?	?	0.5	2
Insecta	Hymenoptera	Formicidae	Acanthomyops	laticeps	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Acropyga	epedana	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Acropyga	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Adetomyrma	sp.2b	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Adlerzia	froggatti	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Aenictus	fergusoni	+	RUSSELL & al. (2009)	Thailand	?	?	1	1
Insecta	Hymenoptera	Formicidae	Aenictus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Aenictus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Aenictus	sp. 1	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Aenictus	sp. 2	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Amblyopone	pallipes	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Amblyopone	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Aneuretus	simoni	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Anillomyrma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Anochetus	mayri	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Anonychomyrma	nitidiceps	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Anoplolepis	gracillipes	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Aphaenogaster	senilis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Aphaenogaster	texana	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Apomyrma	stygia	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Apterostigma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Atopomyrmex	mocquerysi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Atta	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Axinidris	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Azteca	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Bothriomyrmex	hispanicus	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Brachymyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Calomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Calyptomyrmex	beccarii	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Calyptomyrmex	piripillis	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	leonardi	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	ocreatus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	pennsylvanicus	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Camponotus	vicinus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Cardiocondyla	emeryi	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Cardiocondyla	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Carebara	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Carebara	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Carebara	vidua	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Centromyrmex	feae	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Cephalotes	unimaculatus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Cerapachys	augustae	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Colobostruma	unicorna	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Concoctio	concenta	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Crematogaster	navajoa	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Crematogaster	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Crematogaster	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Crematogaster	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Crematogaster	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Cryptopone	gilva	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Cryptopone	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Cyphomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Diacamma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Diacamma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Diacamma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Diacamma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dinoponera	gigantea	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Discothyrea	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Discothyrea	sp. 1	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	imitator	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dorylus	mayri	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dorylus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dorylus	wilverthi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Dorymyrmex	elegans	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Eciton	hamatum	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Ectatomma	brunneum	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Euprenolepis	negrosensis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Eurhopalothrix	philippina	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Eutetramorium	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Forelius	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Formica	occulta	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Formica	whelleri	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Formicoxenus	provancheri	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Froggattella	latispina	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Gnamptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Gnamptogenys	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Goniomma	hispanicum	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Heteroponera	microps	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Heteroponera	panamensis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Hypoponera	inexorata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Iridomyrmex	sp. 1	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Iridomyrmex	spadius	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Labidus	spininodis	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lasius	alienus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptanilla	VB03	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptanilla	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptogenys	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptothorax	rugatulus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Leptothorax	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Linepithema	keiteli	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Liometopum	luctuosum	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lophomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lophomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lophomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lophomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lophomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lophomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lophomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Lordomyrma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Mayriella	transfuga	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Megalomyrmex	latreillei	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Melissotarsus	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Melophorus	sp. 10	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Melophorus	sp. 2	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Meranoplus	mayri	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Messor	bouvieri	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Messor	julianus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Messor	pergandei	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Metapone	madagascaria 1	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Monomorium	chinense	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Monomorium	destructor	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Monomorium	floricola	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myopias	lobosa	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myopopone	castanea	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myrmecia	fulviculis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myrmecocystus	mexicanus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myrmecorhynchus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myrmelachista	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myrmica	incompleta	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myrmicaria	brunnea	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Myrmoteras	williamsi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Mystrium	rogeri	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Neivamyrmex	nigrescens	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Neivamyrmex	rugulosus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Nomamyrmex	esenbecki	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Nothomyrmecia	macrops	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Notonchus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Ochetellus	glaber	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Ocymyrmex	picardi	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontomachus	clarus	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontomachus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontomachus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontomachus	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontoponera	denticulata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontoponera	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontoponera	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Odontoponera	transversa	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Oligomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Oligomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Oligomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Oligomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Oligomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Onychomyrmex	hedleyi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Opisthopsis	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Oxyopomyrmex	insularis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pachycondyla	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pachycondyla	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pachycondyla	stigma	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Papyrius	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Paraponera	clavata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Paratrechina	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	absurda	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	adrianoi	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	allarmata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	amazonica	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole anastasii (syn. of	bilimeki)	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	astur	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	barbata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	biconstricta	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	bilimeki	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	browni	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	buchholzi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	californica	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	caltrop	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	cardiella	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	cocciphaga	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	colobopsis	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole coloradensis (syn. of	pilifera)	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	cuprina	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	desertorium	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	diana	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	diversipilosa	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	dossena	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	dugasi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	elisae	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	erratilis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	fimbriata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	fiorii	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	flavens	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	floridana	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	gagates	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	gatesi	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	hyatti	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	indagatrix	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	indistincta	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	innupta (syn. of alfaroi)	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	jelskii	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	laselva	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	laticornis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	longipes	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	machetula	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	meinerti	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	micula	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	minuscula	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	minutula	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	nitella	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	nitidicollis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	obscurithorax	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	obtusospinosa	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	pallidula	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	pholeops	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	planifrons	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	plinii	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	prostrata	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	quadrensis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	rhea	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	rhinoceros	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	rugulosa	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sagittaria	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sauberi	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sciophila	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	scrobifera	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sensitiva	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sitiens	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	soritis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sospes	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	sp. BCA-01	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	striaticeps	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	subarmata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	tobini	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	tristicula	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	truncula	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	tucsonica (syn. of gilvescens)	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	umphreyi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	vallicola	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	violacea	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	vistana	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	wheeleri	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pheidole	xerophila	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Philidris	cordatus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Philidris	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Philidris	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Philidris	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Philidris	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Philidris	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Plagiolepis	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Platythyrea	bicuspis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Platythyrea	punctata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Podomyrma	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pogonomyrmex	maricopa	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Polyergus	breviceps	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Polyrhachis	armata	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Polyrhachis	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Polyrhachis	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Polyrhachis	vindex	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Ponera	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Ponera	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Prenolepis	imparis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Prionopelta	sp. 2	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pristomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Probolomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Proceratium	sp. 1	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Procryptocerus	batesi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Prolasius	QM.3	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pseudolasius	typhlops	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pseudomyrmex	apache	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Pyramica	pulchella	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Rhoptromyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Rhytidoponera	metallica	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Sericomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Solenopsis	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Solenopsis	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Sphinctomyrmex	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Stenamma	snellingi	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Stigmacros	QM.1	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Stigmacros	QM.3	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Strumigenys	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Tapinoma	opacum	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Technomyrmex	albipes	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Technomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Technomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Technomyrmex	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Temnothorax	tricarinatus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Terataner	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Tetramorium	hispidum	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Tetramorium	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Tetramorium	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Tetramorium	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Tetraponera	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Trachymesopus (Pachycondyla)	darwinii	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Trachymyrmex	jamaicensis	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Tranopelta	subterranea	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Typhlomyrmex	rogenhoferi	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Vollenhovia	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Vollenhovia	sp.	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Wasmannia	sp.	+	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Xenomyrmex	floridenus	–	RUSSELL & al. (2009)
Insecta	Hymenoptera	Formicidae	Solenopsis	electra	–	SHOEMAKER & al. (2000)	Santiago del Estero, Argentina	?	?	0	1
Insecta	Hymenoptera	Formicidae	Solenopsis	geminata	–	SHOEMAKER & al. (2000)	Florida, USA	?	?	0	3
Insecta	Hymenoptera	Formicidae	Solenopsis	interrupta	–	SHOEMAKER & al. (2000)	Santiago del Estero and Cordoba, Argentina	?	?	0	5
Insecta	Hymenoptera	Formicidae	Solenopsis	invicta	+	SHOEMAKER & al. (2000)	Corrientes, Argentina	?	Monogyne	0.86	36
Insecta	Hymenoptera	Formicidae	Solenopsis	macdonaghi	–	SHOEMAKER & al. (2000)	Corrientes, Argentina	?	?	0	2
Insecta	Hymenoptera	Formicidae	Solenopsis	mergergates	+	SHOEMAKER & al. (2000)	Parana, Brazil	?	?	1.0	2
Insecta	Hymenoptera	Formicidae	Solenopsis	quinquecuspis	+	SHOEMAKER & al. (2000)	Santa Fe and Buenos Aires, Argentina	?	?	1.0	7
Insecta	Hymenoptera	Formicidae	Solenopsis	richteri	+	SHOEMAKER & al. (2000)	Mississippi, USA	?	?	0	15
Insecta	Hymenoptera	Formicidae	Solenopsis	saevissima	+	SHOEMAKER & al. (2000)	Goais, Brasil	?	?	1.0	2
Insecta	Hymenoptera	Formicidae	Solenopsis	species X	+	SHOEMAKER & al. (2000)	Santa Fe and Buenos Aires, Agrentina	?	?	0.75	4
Insecta	Hymenoptera	Formicidae	unidentified	species	–	SINTUPACHEE & al. (2006)
Insecta	Hymenoptera	Formicidae	Dolichoderus	coniger	–	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Dolichoderus	gibbifer	–	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Echinopla	pallipes	+	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	extenuata	–	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	allaborans	+	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	attenuata	+	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	binghami	+	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	difficilis	+	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	pilosa	+	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	polita	+	STOLL & al. (2007)
Insecta	Hymenoptera	Formicidae	Tetraponera	penzigi	+	J. RUSSELL UNPUBLISHED DATA Insecta Hymenoptera Formicidae Acromyrmex	echinatior	+	VAN BORM & al. (2001)
Insecta	Hymenoptera	Formicidae	Acromyrmex	insinuator	+	VAN BORM & al. (2001)
Insecta	Hymenoptera	Formicidae	Acromyrmex	octospinosus	+	VAN BORM & al. (2001)
Insecta	Hymenoptera	Formicidae	Atta	cephalotes	+	VAN BORM & al. (2001)
Insecta	Hymenoptera	Formicidae	Atta	colombica	+	VAN BORM & al. (2001)
Insecta	Hymenoptera	Formicidae	Atta	sexdens	+	VAN BORM & al. (2001)
Insecta	Hymenoptera	Formicidae	Atta	texana	+	VAN BORM & al. (2001)
Insecta	Hymenoptera	Formicidae	Formica	aquilonia	+	VILJAKAINEN & al. (2008)
Insecta	Hymenoptera	Formicidae	Formica	lugubris	+	VILJAKAINEN & al. (2008)
Insecta	Hymenoptera	Formicidae	Formica	paralugubris	+	VILJAKAINEN & al. (2008)
Insecta	Hymenoptera	Formicidae	Formica	polyctena	+	VILJAKAINEN & al. (2008)
Insecta	Hymenoptera	Formicidae	Formica	pratensis	+	VILJAKAINEN & al. (2008)
Insecta	Hymenoptera	Formicidae	Formica	rufa	+	VILJAKAINEN & al. (2008)
Insecta	Hymenoptera	Formicidae	Linepithema	humile	–	WEEKS & STOUTHAMER (2003)
Insecta	Hymenoptera	Formicidae	Cataglyphis	cursor	–	WENSELEERS & BILLEN (2000)
Insecta	Hymenoptera	Formicidae	Cataglyphis	piliscapus	–	WENSELEERS & BILLEN (2000)
Insecta	Hymenoptera	Formicidae	Cerapachys	biroi	–	WENSELEERS & BILLEN (2000)
Insecta	Hymenoptera	Formicidae	Messor	capitatus	–	WENSELEERS & BILLEN (2000)
Insecta	Hymenoptera	Formicidae	Platythyrea	punctata	–	WENSELEERS & BILLEN (2000)
Insecta	Hymenoptera	Formicidae	Pristomyrmex	pungens	–	WENSELEERS & BILLEN (2000)
Insecta	Hymenoptera	Formicidae	Acanthomyrmex	ferox	+	WENSELEERS & al. (1998)	Bogor National Reserve	A 	Polygyny&alate queen&independent/budding	?	?
Insecta	Hymenoptera	Formicidae	Acropyga	acutiventris	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Aenictus	javanus	+	WENSELEERS & al. (1998)	?	A 	Monogyny/ergatoid queens&independent/fissioning	?	?
Insecta	Hymenoptera	Formicidae	Aenictus	laeviceps	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Amblyopone	reclinata	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Anoplolepis	gracilipes	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Cardiocondyla	sp.	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Crematogaster	sp.	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Diacamma	rugosum	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Diacamma	sp.	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Dolichoderus	sulcaticeps	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Dolichoderus	thoracicus	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Dorylus	laevigatus	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Gnamptogenys	costata	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Gnamptogenys	dammermani	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Hypoponera	sp.	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Leptanilla	sp. 1	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Leptanilla	sp. 2	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Leptogenys	diminuta	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Leptogenys	myops	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Monomorium	sp. 1	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Monomorium	sp. 2	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Myopias	emeryi	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Myrmecina	sp. A	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Myrmicaria	castanea	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Odontomachus	rixosus	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Odontomachus	simillimus	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pachycondyla	astuta	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Paratrechina	sp. 1	+	WENSELEERS & al. (1998)	Bogor National Reserve	A	alate queen&independent	?	?
Insecta	Hymenoptera	Formicidae	Paratrechina	sp. 2	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Platythyrea	sp.	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pheidole	plagiaria	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pheidole	sp. 1	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pheidole	sp. 2	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pheidole	tandjongensis	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pheidologeton	affinis	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pheidologeton	sp.	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Polyrhachis	cryptoceroides	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Polyrhachis	sp.	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pristomyrmex	brevispinosus	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Probolomyrmex	dammermani	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pseudolasius	sp. 1	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Pseudolasius	sp. 2	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Strumigenys	koningsbergeri	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Strumigenys	sp. 2	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Tapinoma	sp.	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Technomyrmex	butteli	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Tetramorium	kheperra	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Tetramorium	sp.	–	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Tetraponera	sp.	+	WENSELEERS & al. (1998)
Insecta	Hymenoptera	Formicidae	Formica	sp. 1	–	WERREN & WINDSOR (2000)
Insecta	Hymenoptera	Formicidae	Formica	sp. 2	+	WERREN & WINDSOR (2000)
Insecta	Hymenoptera	Formicidae	Leptothroax	sp.	–	WERREN & WINDSOR (2000)
Insecta	Hymenoptera	Formicidae	unidentified	species	+	WERREN & WINDSOR (2000)
Insecta	Hymenoptera	Formicidae	unidentified	species	–	WERREN & al. (1995)
Insecta	Hymenoptera	Formicidae	Ectatomma	tuberculatum	+	WERREN & al. (1995)
Insecta	Hymenoptera	Formicidae	Cataglyphis	sp.	–	ZCHORI-FEIN & PERLMAN (2004)